services:
  redis:
    image: redis:7-alpine
    container_name: nucr-redis
    ports:
      - "6379:6379"

  next-a:
    build: .
    image: nucr-next:latest
    container_name: nucr-next-a
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3000"
    depends_on:
      - redis

  next-b:
    image: nucr-next:latest
    container_name: nucr-next-b
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "3002:3000"
    depends_on:
      - redis
      - next-a
